version: '3'

services:
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    ports:
      - "8081:8081"
    volumes:
      - "./application.properties:/application/application.properties"